# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ArmaRunique <- function(x) {
    .Call(`_esp_ArmaRunique`, x)
}

ArmaDummyMat <- function(mat) {
    .Call(`_esp_ArmaDummyMat`, mat)
}

PredictDummyY <- function(mat, vec) {
    .Call(`_esp_PredictDummyY`, mat, vec)
}

CalculateQ <- function(y_pred, discmat, y) {
    .Call(`_esp_CalculateQ`, y_pred, discmat, y)
}

SLMQ <- function(levelmat, coefs, y) {
    .Call(`_esp_SLMQ`, levelmat, coefs, y)
}

